# Generated by Django 5.2.4 on 2025-08-05 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='published',
            new_name='published_date',
        ),
    ]
