# Generated by Django 5.2.4 on 2025-08-28 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('pasword', models.CharField(max_length=200)),
                ('avatar', models.ImageField(default='images/avatars/noavatar.png', upload_to='images/avatars/')),
            ],
        ),
    ]
