# Generated by Django 5.2.4 on 2025-08-28 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0004_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='pasword',
            new_name='password',
        ),
    ]
